### ISSUE TITLE
Extension options display every time when Chrome is launched.

### ISSUE THREAD

**Issue by jj-tried** [arimgibson/Deadname-Remover#35] opened 2020-07-31 17:01 UTC
This could cause issues, especially for closeted folk, as well as being a minor annoyance.

Wouldn't rule out user error, though.

**Comment by Avakining** [comment] 2020-09-01 19:12
Also occurs randomly when being used in Firefox, even not at launch

**Comment by bria-bloom** [comment] 2022-06-08 23:08
Bumping this, as it occurs for me every time Firefox launches.

**Comment by arimgibson** [comment] 2022-08-03 08:13
Thanks for submitting this @jj-tried , and I appreciate the bump @bria-bloom ! I use Firefox for debugging the extension and have seen this behavior, will install in chrome to check there too. Thinking this is a pretty simple bug, but it might still wait til the version 2.0.0 update which is where I'm putting most of my energy right now. Hoping for that release in just a few weeks

**Comment by arimgibson** [comment] 2022-08-03 18:56
_Excuse my brevity as I catch up on a whole lot of issues that need to be reviewed_

Replicated in Firefox but unable to replicate in Chrome, @jj-tried is this bug still occuring? It's likely that Chrome changed something on their side which fixed this, but Firefox hasn't implemented in

**Comment by Hate9** [comment] 2022-09-09 22:27
This seems to happen for me specifically after every time firefox updates.

**Comment by eluna7** [comment] 2022-09-13 23:23
> This seems to happen for me specifically after every time firefox updates.

very well could be the case! it might line up with why it seems to happen at random. i'll keep an eye out when firefox asks to update and see if it happens after updating.

**Comment by eluna7** [comment] 2022-09-24 03:51
firefox just updated for me! unless the stars happened to align with this bug "randomly" happening after restarting firefox to update it, it seems this bug is caused by firefox updates.

unsure if this also applies to chrome though, sending here since my firefox report was closed as a dupe of this.

**Comment by arimgibson** [comment] 2022-09-24 17:17
Sweet, glad to hear @eluna7 ! I didn't do anything on my end (i.e. release an update), so that sounds likely. I'm still chugging away at that v2 release, but I'll make sure to test for this bug before releasing it. Keeping this issue open until I can confirm it doesn't occur in Chrome or Firefox with v2

**Closed** 2022-11-01 01:38 UTC
Labels: bug

**Comment by eluna7** [comment] 2022-11-02 13:17
@arimgibson this fix did not work on firefox (or wasnt applied to firefox extension?). updated last night before going to bed and when i got up the settings page was opened again. #525 should be reopened since this appears to be a browser unique fix.

**Comment by arimgibson** [comment] 2022-11-02 19:44
That's on me @eluna7; the extension doesn't auto-deploy (yet), and I haven't gotten a chance to manually build, package, and publish it on my side.

I'm on the fence about whether to publish this one or wait until the next major release.... trying to concentrate my energy on the major release right now, although I haven't been able to put in as much time as I wanted!
